### ISSUE TITLE
Panning the map with the dragging starting on cluster marker provoke a zoom

### ISSUE THREAD

**Issue by chifret** [googlearchive/js-marker-clusterer#136]
Hi,

I've noticed that when panning the map, if the initial click of the dragging happens on a cluster marker, it provoke a zoom when the draggins ends.
So, the dragging event is handled as a click for the cluster marker.

I don't know if that's intended, but other google maps controlers don't work the same way.  Maybe a propagation issue somewhere ?

Thanks for the great job done btw !

**Comment by hassam7** [comment]
@chifret 
I think this repo is not maintained anymore. The most active repo which I found is:[Gmap Marker Clusterer Plus](https://github.com/mahnunchik/markerclustererplus)

Anyway I was havin some problem this [stackoverflow answer](https://stackoverflow.com/questions/20684401/marker-clusterer-bug-when-dragging-the-map-many-markers-on-google-maps) helped me, basically you need to add this code 
`google.maps.event.addListener(map,'dragstart',function(){
      mc.zoomOnClick_=false;});
google.maps.event.addListener(map,'mouseup',function(){setTimeout(function(){
      mc.zoomOnClick_=true;},50);});`

Also see this: https://code.google.com/archive/p/google-maps-utility-library-v3/issues/157

**Comment by chifret** [comment]
You're right, it's even marked so on the GitHub description...

Thanks for the mention, and for the code.  The lil' hack will serve :)
