### ISSUE TITLE
Hide cluster dynamically once all markers are hidden

### ISSUE THREAD

**Issue by Remo** [googlearchive/js-marker-clusterer#31]
I'm using a toggle button to hide/show certain markers. Those that are part of a cluster have a problem. If I dyncamically hide `marker.setVisible(false/true)` all markers of a cluster the cluster stays visible.

I tried to call `redraw` and `repaint`, but both methods don't seem to consider the visibility of the marker. Any ideas about the correct way to do that?

**Comment by Remo** [comment]
Created a PR that works so far, requires more testing, CLA and so on.. Code will only work if `repaint` is called after changing the markers visibility

**Comment by Remo** [comment]
this PR does the trick for me https://github.com/googlemaps/js-marker-clusterer/pull/33

**Comment by Remo** [comment]
This has been implemented here https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer

**Comment by zelds** [comment]
Hi. Have same trouble while using https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js   ?

**Comment by Remo** [comment]
@zelds have you seen my comment above? You are using an unsupported version, try ours at https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer
