### ISSUE TITLE
markers_ undefined

### ISSUE THREAD

**Issue by aduptoro** [googlearchive/js-marker-clusterer#37]
On line 1015 there is a markers_ variable which is not defined, should be markers without _.

regards,
Tom

**Comment by husayt** [comment]
All examples are broken and our website is broken too. Library is broken completely

**Comment by luukdv** [comment]
Same issure here. Temporary fix: depending on one of the previous commits, for example

`"js-marker-clusterer": "git://github.com/googlemaps/js-marker-clusterer.git#472bf7b56307b0caa0c28b0fb65d6c0b392b3c5b"`

**Comment by LasseRafn** [comment]
Any updates? :/

**Comment by GuillaumeLeclerc** [comment]
We are impacted too GuillaumeLeclerc/vue-google-maps#10. 

I will use the fix from @luukdv temporarly.
