### ISSUE TITLE
Marker Clusterer icons are gone. Solved.

### ISSUE THREAD

**Issue by mluis** [googlearchive/js-marker-clusterer#59]
Marker Clusterer icons are gone because they link to the old repository.
Changing the URL to the one below solves the issue:

https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m

**Comment by diogolast** [comment]
thanks!!

**Comment by ghost** [comment]
Two other issues already mention this (and include solutions): #55 #54

**Comment by nivas90** [comment]
When can we expect to see the commit done on the main branch? This is currently breaking our application. 
Thanks

**Comment by yannbug** [comment]
+1

**Comment by djozsef** [comment]
GitHub is not a CDN. You should host the image files on your own and set imagePath option.

**Comment by mluis** [comment]
@djozsef perhaps the link should be this one? 

https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m

**Comment by djozsef** [comment]
@mluis Sound like a plan! I am not sure if it is a proper canonical way but should work even in master as default `imagePath`.

**Comment by davidpelayo** [comment]
This unplanned change has caused bugs on thousand of applications. I consider resources shouldn't have been deleted, though.

**Comment by mluis** [comment]
That's out of my realm but I agree that this should have been a soft handover.

**Comment by davidpelayo** [comment]
@mluis we have currently thousand of sites published ([of our clients](http://lodgify.com)) which are visually failing because of this.... I mean, I thought these things were more serious within the different google organization departments...

**Comment by ghost** [comment]
@davidpelayo I fully understand you, but "failing" is maybe a bit much. The markerclusterer still works, it's just the images that don't show up.

**Comment by davidpelayo** [comment]
@WACMemphis I agree. It depends on what you mean by saying failing.

However, the responsibility of these actions considering how many people have been using this solution for production-apps it's high enough for double-checking beforehand.

**Comment by ghost** [comment]
@davidpelayo Yes, I'm with you on this. I have to update quite a few applications myself.
I'm opting to use my own images from now on though.

BTW, left a comment on your commit.

**Comment by brianhogg** [comment]
I've been passing in the MAPPARAMS.imageurl var to set your local path to the images, but the markerclusterer_compiled.js script (or _packed.js in the old version) does not seem to look at this.  It appears to be hard coded to the googlecode.com repo.

The attached minified version does the trick.
[markerclusterer.min.js.zip](https://github.com/googlemaps/js-marker-clusterer/files/264244/markerclusterer.min.js.zip)

**Comment by wedneyyuri** [comment]
> GitHub is not a CDN. You should host the image files on your own and set imagePath option.

In my opinion, the `imagePath` option should be optional but throw a warning if not passed.

**Comment by bunnyhero** [comment]
> GitHub is not a CDN. You should host the image files on your own and set imagePath option.

It's broken even on the documentation site's example pages :) (e.g. https://googlemaps.github.io/js-marker-clusterer/examples/simple_example.html )

**Comment by KashifAhmed** [comment]
For time being replace MARKER_CLUSTER_IMAGE_PATH_ with 
'https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m'

This trick work for me.

**Comment by philipdbrown** [comment]
When instantiating the MarkerClusterer, you can pass a new path to the image set with the imagePath option:

```
var mc = new MarkerClusterer(map, makers, {imagePath: 'https://www.mydomain.com/m'});
```

that is also a quick fix.  Although you can still change the js-marker-cluster, but I like to keep that clean.  Just my thoughts.

**Comment by PeterTheOne** [comment]
fixed by 2f659a3

**Comment by sudheerec107** [comment]
Suppose if i have many clusters in my map and i want clusters with different color depending on some value. How to achieve this.

**Comment by cmcintosh** [comment]
You probably could extend the class for this, im not sure what you would 
use to decide which cluster gets which icon, but should be a simple 
addition of a if check.

**Comment by javiersuazomatus** [comment]
For javascript I recommend this way:

`return !myStr ? null : myStr.replace(/([A-Z])/g, function (g) { return '-' + g[0].toLowerCase() });`

**Comment by thames91** [comment]
All of these result in a not-found now. Thanks google.

**Comment by sebastiangug** [comment]
All of the links in this thread are 404 now.

Thanks google.
