### ISSUE TITLE
Cluster icon location incorrect to most markers

### ISSUE THREAD

**Issue by kshipp** [googlearchive/js-marker-clusterer#76]
I've found that the calculation(?) of the location of the cluster icon to be incorrect at times.  I've attached two screenshots.  
Map1 = you can see 28 locations at the Oklahoma and Arkansas border (which is incorrect). Only ONE location is near there.
Map 2 = shows the zoom when clicking on Map1 ("28" icon).  Notice that the Clusterer placed the cluster icon near the Ft. Smith (far left) marker, instead of where it should, either a)..centrally located among all 28 locations, or b)..at the next-largest-cluster (26).  Ideally, the cluster icon position needs to be central to all the underlying markers.  It looks like it's just choosing a random marker position to represent its location?

Map1 incorrectly shows all the locations too far west Arkansas, whereas 90% of them are exactly central Arkansas.
![map1](https://cloud.githubusercontent.com/assets/749846/15652684/88279e6a-264d-11e6-8212-d401d17002ba.png)
![map2](https://cloud.githubusercontent.com/assets/749846/15652686/8a7e2da0-264d-11e6-9986-8eaddf395ace.png)

**Comment by PeterTheOne** [comment]
Set the `averageCenter` option to `true`, it is set to `false` by default. Maybe it should be set to `true` by default. Other than that this is intended behavior and this issue can be closed.

**Comment by kshipp** [comment]
PeterTheOne - awesome!  I'll give that a try. Thanks for sharing this info.  I agree - should be defaulted to True.

**Comment by kshipp** [comment]
After adding averageCenter option to true, it works perfectly.  Thanks!

![map3](https://cloud.githubusercontent.com/assets/749846/15652898/0b616080-264f-11e6-9401-d44df81126a1.png)
